@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
@idQuestion = {{fetch_recent_questions.response.body.questions[0].id}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Maria",
    "email": "maria@gazin.com",
    "password": "123123"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "maria@gazin.com",
    "password": "123123"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Nova pergunta2",
    "content": "Teste2"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_answer
POST {{baseUrl}}/questions/{{idQuestion}}/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "content": "New Answer2"
}

###

# @name fetch_question_answers
GET {{baseUrl}}/questions/{{idQuestion}}/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}
